{"isMarkdown":true,"isTranslated":false,"isActive":true,"flaws":{},"title":"Promise.prototype.catch()","mdn_url":"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch","locale":"en-US","native":"English (US)","browserCompat":["javascript.builtins.Promise.catch"],"summary":"The catch() method of Promise instances schedules a function to be called when the promise is rejected. It immediately returns an equivalent Promise object, allowing you to chain calls to other promise methods. It is a shortcut for Promise.prototype.then(undefined, onRejected).","popularity":0.0485,"modified":"2023-10-06T00:54:00.000Z","source":{"folder":"en-us/web/javascript/reference/global_objects/promise/catch","github_url":"https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/catch/index.md","last_commit_url":"https://github.com/mdn/content/commit/e85b95300b7817bd048b54729a5e69a289828e84","filename":"index.md"},"short_title":"Promise.prototype.catch()","parents":[{"uri":"/en-US/docs/Web","title":"References"},{"uri":"/en-US/docs/Web/JavaScript","title":"JavaScript"},{"uri":"/en-US/docs/Web/JavaScript/Reference","title":"Reference"},{"uri":"/en-US/docs/Web/JavaScript/Reference/Global_Objects","title":"Standard built-in objects"},{"uri":"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise","title":"Promise"},{"uri":"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch","title":"Promise.prototype.catch()"}],"pageTitle":"Promise.prototype.catch() - JavaScript | MDN","noIndexing":false,"hash":"88e5c543a07e122dbf484c24bd490e8fe0bffca630de08eb1d7d52e036387478"}